
#include "../unit_list_structs.h"

unit_voice_file_list_info Astray_Red_Frame_Custom_inject_unit_voice_file_list_info();
unit_voice_hash_list_0x28 Astray_Red_Frame_Custom_inject_arcade_select_hash();
unit_voice_hash_list_0x14 Astray_Red_Frame_Custom_inject_arcade_continue_no_hash();
unit_voice_hash_list_0x18 Astray_Red_Frame_Custom_inject_arcade_continue_prompt_hash();
unit_voice_hash_list_0x28 Astray_Red_Frame_Custom_inject_arcade_continue_yes_hash();
unit_voice_hash_list_0x8 Astray_Red_Frame_Custom_inject_bandai_namco_games_serifu_hash();
unit_hash_info Astray_Red_Frame_Custom_inject_unit_hash_info();
unit_unk_enum_info Astray_Red_Frame_Custom_inject_unk_enum();
unit_update_unit_id_list Astray_Red_Frame_Custom_inject_gundam_update_unit_ID_list();
unit_update_unit_id_list Astray_Red_Frame_Custom_inject_update_unit_ID_list_2();
unit_string_info Astray_Red_Frame_Custom_inject_string();

                        