
#include "../unit_list_structs.h"

unit_voice_file_list_info extreme_gundam_Mk_II_AXE_inject_unit_voice_file_list_info();
unit_voice_hash_list_0x28 extreme_gundam_Mk_II_AXE_inject_arcade_select_hash();
unit_voice_hash_list_0x14 extreme_gundam_Mk_II_AXE_inject_arcade_continue_no_hash();
unit_voice_hash_list_0x18 extreme_gundam_Mk_II_AXE_inject_arcade_continue_prompt_hash();
unit_voice_hash_list_0x28 extreme_gundam_Mk_II_AXE_inject_arcade_continue_yes_hash();
unit_voice_hash_list_0x8 extreme_gundam_Mk_II_AXE_inject_bandai_namco_games_serifu_hash();
unit_hash_info extreme_gundam_Mk_II_AXE_inject_unit_hash_info();
unit_unk_enum_info extreme_gundam_Mk_II_AXE_inject_unk_enum();
unit_update_unit_id_list extreme_gundam_Mk_II_AXE_inject_gundam_update_unit_ID_list();
unit_update_unit_id_list extreme_gundam_Mk_II_AXE_inject_update_unit_ID_list_2();
unit_string_info extreme_gundam_Mk_II_AXE_inject_string();