
#include "../unit_list_structs.h"

unit_voice_file_list_info Wing_Gundam_Snow_White_Prelude_inject_unit_voice_file_list_info();
unit_voice_hash_list_0x28 Wing_Gundam_Snow_White_Prelude_inject_arcade_select_hash();
unit_voice_hash_list_0x14 Wing_Gundam_Snow_White_Prelude_inject_arcade_continue_no_hash();
unit_voice_hash_list_0x18 Wing_Gundam_Snow_White_Prelude_inject_arcade_continue_prompt_hash();
unit_voice_hash_list_0x28 Wing_Gundam_Snow_White_Prelude_inject_arcade_continue_yes_hash();
unit_voice_hash_list_0x8 Wing_Gundam_Snow_White_Prelude_inject_bandai_namco_games_serifu_hash();
unit_hash_info Wing_Gundam_Snow_White_Prelude_inject_unit_hash_info();
unit_unk_enum_info Wing_Gundam_Snow_White_Prelude_inject_unk_enum();
unit_update_unit_id_list Wing_Gundam_Snow_White_Prelude_inject_gundam_update_unit_ID_list();
unit_update_unit_id_list Wing_Gundam_Snow_White_Prelude_inject_update_unit_ID_list_2();
unit_string_info Wing_Gundam_Snow_White_Prelude_inject_string();

                        